apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jupyterhub
  namespace: jupyterhub-test
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: jupyterhub
  namespaceSelector:
    matchNames:
      - jupyterhub-test
  endpoints:
    - port: api
      interval: 30s


