apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub-test
---
# Service account used by the JupyterHub Helm chart
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-sa
  namespace: jupyterhub-test
---
# Minimal RBAC for JupyterHub and single-user pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-role
  namespace: jupyterhub-test
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-rb
  namespace: jupyterhub-test
subjects:
  - kind: ServiceAccount
    name: jupyterhub-sa
    namespace: jupyterhub-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub-role


