apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-home
  namespace: jupyterhub-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  # Adjust this to match the storage class available in the cluster
  storageClassName: standard


